# docker-compose.yml
services:
  app:
    build: .
    depends_on:
      - cassandra
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra  # use service name!

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml  # Mount custom config
    environment:
        - CASSANDRA_CLUSTER_NAME=MyCluster
        - CASSANDRA_DC=datacenter1
        - CASSANDRA_RACK=rack1
        - cassandra-data:/var/lib/cassandra
volumes:
  cassandra-data:
